webserver:
  host_address: "0.0.0.0"
  port: "5000"
  debug: "0"
  logging_level: "ERROR"
  static_folder: "build/static"
  template_folder: "build"

neural_network:
  "1": "/weights/neural_network_weights"
  "2": "/weights/neural_network_weights"
  "3": "/weights/neural_network_weights"
  "4": "/weights/neural_network_weights"